application: testingbags
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/images
  static_dir: static/images

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js


- url: /static/favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static
  
- url: .*
  script: main.app